language: rust
matrix:
  include:
    - rust: 1.37.0
    - rust: stable
cache:
  directories:
  - $HOME/.cargo
  - ./target # OK to cache because `cargo` will pick up changes to the project.
script: cargo test
