[package]
name = "ocean-cli"
description = "Command-line interface for the Ocean package manager."
version = "0.0.0"
authors = ["The Ocean Project Developers"]
license = "Apache-2.0"
readme = "README.md"
edition = "2018"
homepage = "https://www.oceanpkg.org"
publish = false

[[bin]]
name = "ocean"
path = "src/main.rs"

[dependencies.oceanpkg]
path = "../lib"
version = "0.0.9"
features = ["toml"]

[dependencies]
clap = "2.33"
dirs = "1"
failure = "0.1.6"
reqwest = "0.9.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2.1"
