#!/usr/bin/env bash

# This file should never have the execution bit set, to demonstrate Ocean being
# able to install and run it without.

echo "The answer to the question of the meaning of life, the universe, and everything is..."
sleep 1
echo "42"
